## 00.pyTorch Fundamentals

Resource notebook:https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.8.0+cu126


## Introduction to Tensors

### creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
# Vector

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX(MATRIX,TENSOR는 대문자로 적어야함. scalar,vector는 소문자)
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#tensor(대문자로 적어야)
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
tensor.ndim


3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

###Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> lokk at data -> update random numbers'

In [16]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.7187, 0.1322, 0.8561, 0.8739],
         [0.3193, 0.0594, 0.9854, 0.5728],
         [0.2675, 0.5256, 0.7610, 0.8821]]])

In [17]:
random_tensor.ndim

3

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [90]:
one = torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [24]:
# use torch.range() and get deprecated message, use torch,arange()
one_to_ten = torch.arange(start=0,end=10,step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note** Tensor datatypes is one of the 3 big errors with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors on the right device

In [26]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, #what datatype is the tensor(e.g.)
                               device=None,# what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations)
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
a = float_16_tensor*float_32_tensor
a.dtype

torch.float32

In [30]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)

In [31]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors(tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors on the right device - to get device from a tensor,can use 'tensor.device'

In [32]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2752, 0.0397, 0.6285, 0.6034],
        [0.3362, 0.0710, 0.1548, 0.0200],
        [0.0635, 0.4253, 0.4285, 0.3869]])

In [33]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [34]:
# find out deetails about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.2752, 0.0397, 0.6285, 0.6034],
        [0.3362, 0.0710, 0.1548, 0.0200],
        [0.0635, 0.4253, 0.4285, 0.3869]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu



### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication



In [35]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [36]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [37]:
tensor

tensor([1, 2, 3])

In [38]:
# Substract 10
tensor -10

tensor([-9, -8, -7])

In [39]:
# Try out Pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [40]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in nueral networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication(dot product)

There are two main rules that performing matrix multiplicaion needs to satisfy:
1. The **inner dimensions** must match:
* '(3,2) @ (3,2)' won't work
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work
2. The resulting matirix has the shape of the **outer dimentions**:
* '(2,3) @ (3,2)' -> '(2,2)'
* '(3,2) @ (2,3)' -> '(3,3)'

In [41]:
# Element wise multiplication
print(tensor, "*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [42]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [43]:
tensor

tensor([1, 2, 3])

In [44]:
# Matrix multiplication by  hand
1*1 + 2*2 + 3*3

14

In [45]:
tensor @ tensor

tensor(14)

In [46]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] *tensor[i]
print(value)

tensor(14)
CPU times: user 1.04 ms, sys: 0 ns, total: 1.04 ms
Wall time: 1.63 ms


In [47]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 61 µs, sys: 0 ns, total: 61 µs
Wall time: 64.1 µs


tensor(14)

### One of the most common errors in deep learning:shape errors

In [48]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#torch.mm(tensor_A,tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [50]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor

In [51]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [52]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [53]:
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

In [54]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A ={tensor_A.shape},tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutpur shape: {output.shape}")



Original shapes: tensor_A =torch.Size([3, 2]),tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Outpur shape: torch.Size([3, 3])


##Finding the min,max,mean,sum,etc(tensor aggregation)

In [55]:
# Create a tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [56]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [57]:
#Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [58]:
#Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [59]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [60]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [61]:
#Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [62]:
x[0]

tensor(1)

In [63]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [64]:
x[9]

tensor(91)

## Reshaping, stacking, sqeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* view - Return a view of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each othe (vstack) or side by side(hstack)
* Squeeze - removes all '1' dimensions from a tensor
* unsqueeze - add a '1' dimension to a target tensor
* permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [97]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [98]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [99]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [100]:
#Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [104]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [103]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [70]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\n New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])

 New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [71]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [72]:
# torch.permute - rearranges thedimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # {height, width,colour_channels}

# permute original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0 ->1, 1->2, 2->0

print(f"Previous sahpe: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous sahpe: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [73]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with Pythorch is similar to indexing with Numpy

In [74]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [75]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [76]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [77]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [78]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [79]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [80]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1,1]

tensor([5])

In [81]:
# Get index 0 of 0th and 1st dimension and all values of wnd dimension
x[0,0,:]

tensor([1, 2, 3])

In [82]:
# Index on x to return 9
x[0,2,2]
# Index on x to return 3.6.9
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors & Numpy

NumPy is a popular scientific python numerical computiong library.

And because of this, Pytorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor ->'torch.from_numpy(ndarray)'
* Pytorch tensor -> NumPy-> torch.Tensor.numpy()

In [83]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32) #warning when converting from numpy -> pytorch,pytorch reflects numpy's default datatype of float64 unless specified otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [84]:
#change the value of array, what will this do to 'tensor'?
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [85]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [86]:
numpy_tensor.dtype

dtype('float32')

In [87]:
# Change the tensor, what happens to 'numpy_tensor?
tensor =tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

'start with randon numbers -> tensor operations -> update random numbers to try and
make them better representations of the data -> again -> again -> again... '

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does id "flavour" the randomness.

In [108]:
import torch

#Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.7788, 0.0213, 0.4144, 0.8917],
        [0.1819, 0.8767, 0.7008, 0.7741],
        [0.1369, 0.5292, 0.8778, 0.1490]])
tensor([[0.4211, 0.7289, 0.3996, 0.3826],
        [0.9237, 0.2455, 0.3274, 0.3195],
        [0.4485, 0.2494, 0.0577, 0.5251]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [115]:
# Let's make some random but reproducible tensors
import torch

#set the random seed
RANDOM_SEED = 100
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(100)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware +PyThorch working behind the scenes to make eveything hunky

### 1. Getting a GPU

1. Easiest - use Google Colab for a free GPU.(options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's a lot of options
3. Use cloud computing - GCP,AWS,Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch +gpu drivers (CUDA) takes a little bit of setting up, to do this,refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [1]:
!nvidia-smi

Wed Sep 10 01:50:50 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

2. Check for GPU access with PyTorch

In [2]:
#check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU,it's best practice to setup device agnosic code: https://docs.pytorch.org/docs/stable/notes/cuda.html

E.g. run on GPU if available, else default to CPU

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [6]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], )

# Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# Move tensor to GPu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [9]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
# To fix the GPU tensor with MunPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [11]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-Curriculum
see exercise: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises


9/8 1시간 54분까지 시청함

9/9 3:44:45
